<?php
/**
 *                       ######
 *                       ######
 * ############    ####( ######  #####. ######  ############   ############
 * #############  #####( ######  #####. ######  #############  #############
 *        ######  #####( ######  #####. ######  #####  ######  #####  ######
 * ###### ######  #####( ######  #####. ######  #####  #####   #####  ######
 * ###### ######  #####( ######  #####. ######  #####          #####  ######
 * #############  #############  #############  #############  #####  ######
 *  ############   ############  #############   ############  #####  ######
 *                                      ######
 *                               #############
 *                               ############
 *
 * Adyen Subscription module (https://www.adyen.com/)
 *
 * Copyright (c) 2015 H&O E-commerce specialists B.V. (http://www.h-o.nl/)
 * See LICENSE.txt for license details.
 *
 * Author: Adyen <magento@adyen.com>, H&O E-commerce specialists B.V. <info@h-o.nl>
 */
?>
<?php /** @var Adyen_Subscription_Block_Adminhtml_Subscription_View_Tabs_Info $this */ ?>
<?php $_subscription = $this->getSubscription(); ?>
<?php $_billingAgreement = $this->getBillingAgreement(); ?>

<div class="box-left">
    <!--General Info-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-general-info"><?php echo Mage::helper('adyen_subscription')->__('General Information'); ?></h4>
        </div>
    </div>
    <div class="fieldset">
        <table cellspacing="0" class="form-list">
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Customer') ?></label></td>
                <td class="value">
                    <a href="<?php echo $this->getCustomerViewUrl(); ?>" target="_blank">
                        <strong><?php echo $this->escapeHtml($_subscription->getCustomerName()); ?></strong>
                    </a>
                </td>
            </tr>
            <tr>
                <td class="label"><label><?php echo Mage::helper('adyen_subscription')->__('Status'); ?></label></td>
                <td class="value"><?php echo $_subscription->renderStatusBar();?></td>
            </tr>
            <?php if ($_subscription->getErrorMessage()): ?>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('adyen_subscription')->__('Error Message'); ?></label></td>
                    <td class="value"><?php echo $_subscription->getErrorMessage();?></td>
                </tr>
            <?php endif; ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('adyen_subscription')->__('Created from'); ?></label></td>
                <td class="value"><strong><?php echo $this->getStoreName(); ?></strong></td>
            </tr>
        </table>
    </div>
</div>
<div class="box-right">
    <!--Subscription Info-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-subscription-info"><?php echo Mage::helper('adyen_subscription')->__('Adyen Subscription Information'); ?></h4>
        </div>
    </div>
    <div class="fieldset">
        <table cellspacing="0" class="form-list">
            <tr>
                <td class="label"><label><?php echo Mage::helper('adyen_subscription')->__('Created at'); ?></label></td>
                <td class="value"><strong><?php echo $_subscription->getCreatedAtFormatted(); ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label><?php echo Mage::helper('adyen_subscription')->__('Updated at'); ?></label></td>
                <td class="value"><strong><?php echo $_subscription->getUpdatedAtFormatted(); ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label><?php echo Mage::helper('adyen_subscription')->__('Scheduled Order'); ?></label></td>
                <td class="value">
                    <?php if ($_subscription->getScheduledAt()): ?>
                        <strong><?php echo $_subscription->getScheduledAtFormatted(); ?></strong>
                    <?php else: ?>
                        <strong><?php echo $this->__('Not Scheduled') ?></strong>
                    <?php endif; ?>
                </td>
            </tr>
            <tr>
                <td class="label"><label><?php echo Mage::helper('adyen_subscription')->__('Period'); ?></label></td>
                <td class="value"><strong><?php echo $_subscription->getTermLabel(); ?></strong></td>
            </tr>
            <?php if ($_subscription->getEndsAt()): ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('adyen_subscription')->__('Runs until'); ?></label></td>
                <td class="value"><strong><?php echo $_subscription->getEndsAtFormatted(); ?></strong></td>
            </tr>
            <?php endif; ?>
        </table>
    </div>
</div>
<div class="clear"></div>

<div class="box-left">
    <!--Billing Address-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-billing-address"><?php echo Mage::helper('sales')->__('Billing Address') ?></h4>
        </div>
        <fieldset>
            <address><?php echo $_subscription->getBillingAddress()->format('html'); ?></address>
        </fieldset>
    </div>
</div>
<div class="box-right">
    <!--Shipping Address-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-shipping-address"><?php echo Mage::helper('sales')->__('Shipping Address') ?></h4>
        </div>
        <fieldset>
            <address><?php echo $_subscription->getShippingAddress()->format('html'); ?></address>
        </fieldset>
    </div>
</div>
<div class="clear"></div>

<div class="box-left">
    <!--Payment Info-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-billing-address"><?php echo Mage::helper('adyen_subscription')->__('Billing Agreement Information'); ?></h4>
        </div>

        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <?php if ($_billingAgreement->getId()): ?>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('adyen_subscription')->__('Reference ID'); ?></label></td>
                    <td class="value">
                        <a href="<?php echo $this->getBillingAgreementViewUrl();?>" target="_blank">
                            <strong><?php echo $_billingAgreement->getReferenceId(); ?></strong>
                        </a>
                    </td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('adyen_subscription')->__('Status'); ?></label></td>
                    <td class="value"><strong><?php echo $_billingAgreement->getStatusLabel(); ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('adyen_subscription')->__('Method'); ?></label></td>
                    <td class="value"><strong><?php echo $_billingAgreement->getPaymentMethodInstance() ? $_billingAgreement->getPaymentMethodInstance()->getTitle() : ''; ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('adyen_subscription')->__('Created At'); ?></label></td>
                    <td class="value"><strong><?php echo $_billingAgreement->getCreatedAt(); ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('adyen_subscription')->__('Label'); ?></label></td>
                    <td class="value"><strong><?php echo $_billingAgreement->getAgreementLabel(); ?></strong></td>
                </tr>
                <?php else: ?>
                <tr>
                    <td class="label"><em></em><?php echo Mage::helper('adyen_subscription')->__('No Billing Agreement'); ?></em></td>
                </tr>
                <?php endif; ?>
            </table>
        </div>
    </div>
</div>
<div class="box-right">
    <!--Shipping Info-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-shipping-address"><?php echo Mage::helper('adyen_subscription')->__('Shipping &amp; Handling Information'); ?></h4>
        </div>
    </div>
    <div class="fieldset">
        <table cellspacing="0" class="form-list">
            <tr>
                <td class="label"><label><?php echo Mage::helper('adyen_subscription')->__('Shipping Method Code'); ?></label></td>
                <td class="value"><strong><?php echo $_subscription->getShippingMethod(); ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label><?php echo Mage::helper('adyen_subscription')->__('Shipping Method Title'); ?></label></td>
                <td class="value"><strong><?php echo $_subscription->getShippingMethodTitle(); ?></strong></td>
            </tr>
        </table>
    </div>
</div>

<div class="clear"></div>

<!--Subscription Products-->
<div class="edit-entry">
    <div class="entry-edit-head">
        <h4 class="icon-head"><?php echo Mage::helper('adyen_subscription')->__('Adyen Subscription Products'); ?></h4>
    </div>
    <?php echo $this->getChildHtml('subscription_products'); ?>
</div>
