<?php
/**
 *                       ######
 *                       ######
 * ############    ####( ######  #####. ######  ############   ############
 * #############  #####( ######  #####. ######  #############  #############
 *        ######  #####( ######  #####. ######  #####  ######  #####  ######
 * ###### ######  #####( ######  #####. ######  #####  #####   #####  ######
 * ###### ######  #####( ######  #####. ######  #####          #####  ######
 * #############  #############  #############  #############  #####  ######
 *  ############   ############  #############   ############  #####  ######
 *                                      ######
 *                               #############
 *                               ############
 *
 * Adyen Subscription module (https://www.adyen.com/)
 *
 * Copyright (c) 2015 H&O E-commerce specialists B.V. (http://www.h-o.nl/)
 * See LICENSE.txt for license details.
 *
 * Author: Adyen <magento@adyen.com>, H&O E-commerce specialists B.V. <info@h-o.nl>
 */
?>
<?php /** @var Adyen_Subscription_Block_Customer_Subscription_List $this */ ?>

<?php echo $this->getMessagesBlock()->toHtml() ?>

<?php $_subscriptions = $this->getSubscriptions(); ?>
    <div class="page-title">
        <h1><?php echo $this->__('My Subscriptions') ?></h1>
    </div>
<?php echo $this->getPagerHtml(); ?>
<?php if($_subscriptions->getSize()): ?>
    <table class="data-table" id="my-subscriptions-table">
        <col width="1" />
        <col width="1" />
        <col />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <thead>
        <tr>
            <th><?php echo $this->__('Subscription #') ?></th>
            <th><?php echo $this->__('Status') ?></th>
            <th><?php echo $this->__('Ship To'); ?></th>
            <th><?php echo $this->__('Created At') ?></th>
            <th><?php echo $this->__('Next Order At') ?></th>
            <th><?php echo $this->__('Period') ?></th>
            <th><?php echo $this->__('Billing Agreement') ?></th>
            <th>&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($_subscriptions as $_subscription): ?>
            <?php /** @var Adyen_Subscription_Model_Subscription $_subscription */ ?>
            <tr>
                <td>#<?php echo $_subscription->getId() ?></td>
                <td><em><?php echo ucfirst($_subscription->getStatusLabel()); ?></em></td>
                <td><?php echo $_subscription->getShippingAddress()->getName(); ?></td>
                <td><?php echo $_subscription->getCreatedAtFormatted(false); ?></td>
                <td><?php echo $_subscription->getScheduledAtFormatted(false); ?></td>
                <td><span class="nobr"><?php echo $_subscription->getTermLabel(); ?></span></td>
                <td><a href="<?php echo $this->getAgreementUrl($_subscription); ?>">
                        <?php echo $_subscription->getBillingAgreement()->getReferenceId(); ?></a>
                </td>
                <td><a href="<?php echo $this->getViewUrl($_subscription) ?>">
                        <?php echo $this->__('View Subscription') ?></a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <script type="text/javascript">decorateTable('my-subscriptions-table');</script>
    <?php echo $this->getPagerHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__("You don't have any subscriptions yet."); ?></p>
<?php endif ?>