<?php
/**
 *                       ######
 *                       ######
 * ############    ####( ######  #####. ######  ############   ############
 * #############  #####( ######  #####. ######  #############  #############
 *        ######  #####( ######  #####. ######  #####  ######  #####  ######
 * ###### ######  #####( ######  #####. ######  #####  #####   #####  ######
 * ###### ######  #####( ######  #####. ######  #####          #####  ######
 * #############  #############  #############  #############  #####  ######
 *  ############   ############  #############   ############  #####  ######
 *                                      ######
 *                               #############
 *                               ############
 *
 * Adyen Subscription module (https://www.adyen.com/)
 *
 * Copyright (c) 2015 H&O E-commerce specialists B.V. (http://www.h-o.nl/)
 * See LICENSE.txt for license details.
 *
 * Author: Adyen <magento@adyen.com>, H&O E-commerce specialists B.V. <info@h-o.nl>
 */
?>
<?php /* @var Adyen_Subscription_Block_Customer_Subscriptions_View $this */ ?>
<?php $_subscription = $this->getSubscription(); ?>
<div class="page-title title-buttons subscription-view-header-wrapper">
    <h1 class="heading"><?php echo $this->__('Subscription # %s', $this->escapeHtml($_subscription->getId())); ?></h1>
    <?php if ($this->getCanCancel()): ?>
        <button type="button" title="<?php echo $this->__('Cancel') ?>" class="button" onclick="window.location.href = '<?php echo $this->getCancelUrl() ?>';"><span><span><?php echo $this->__('Cancel') ?></span></span></button>
    <?php endif; ?>
    <?php if ($this->getCanPause()):

        $extraStyle = "";
        if($this->getCanCancel()) {
            $extraStyle = "style=\"right:95px; \" ";
        } ?>
        <button <?php echo $extraStyle; ?>type="button" title="<?php echo $this->__('Pause') ?>" class="button" onclick="window.location.href = '<?php echo $this->getPauseUrl() ?>';"><span><span><?php echo $this->__('Pause') ?></span></span></button>
    <?php endif; ?>
    <?php if ($this->getCanResume()): ?>
        <button type="button" title="<?php echo $this->__('Resume') ?>" class="button" onclick="window.location.href = '<?php echo $this->getResumeUrl() ?>';"><span><span><?php echo $this->__('Resume') ?></span></span></button>
    <?php endif; ?>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<div class="subscription">
    <div class="info-box subscription-details">
        <h2 class="box-title"><?php echo $this->__('Subscription Information') ?></h2>
        <div class="box-content">
            <table class="info-table">
                <tbody>
                <tr>
                    <th><?php echo $this->__('Reference ID:') ?></th>
                    <td><?php echo $this->escapeHtml($_subscription->getId()); ?></td>
                </tr>
                <tr>
                    <th><?php echo $this->__('Status:') ?></th>
                    <td><?php echo ucfirst($_subscription->getStatusLabel()); ?></td>
                </tr>
                <tr>
                    <th><?php echo $this->__('Created At:') ?></th>
                    <td><?php echo $this->escapeHtml($_subscription->getCreatedAtFormatted()); ?></td>
                </tr>
                <tr>
                    <th><?php echo $this->__('Updated At:') ?></th>
                    <td><?php echo $this->escapeHtml($_subscription->getUpdatedAtFormatted()); ?></td>
                </tr>
                <tr>
                    <th><?php echo $this->__('Next Order At:') ?></th>
                    <td><?php echo $this->escapeHtml($_subscription->getScheduledAtFormatted()); ?></td>
                </tr>
                <tr>
                    <th><?php echo $this->__('Period:') ?></th>
                    <td><?php echo $this->escapeHtml($_subscription->getTermLabel()); ?></td>
                </tr>
                <tr>
                    <th><?php echo $this->__('Billing Agreement:') ?></th>
                    <td><a href="<?php echo $this->getUrl('sales/billing_agreement/view', array('agreement' => $_subscription->getBillingAgreementId())); ?>">
                            <?php echo $_subscription->getBillingAgreement()->getReferenceId(); ?></a>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

    <?php $upcomingOrders = $this->getUpcomingOrders();?>

    <?php if(count($upcomingOrders) > 0): ?>

        <h2 class="table-caption"><?php echo $this->__('Upcoming Orders') ?></h2>
        <ul>
            <?php foreach ($upcomingOrders as $date): ?>
                <li><?php echo Mage::helper('core')->formatDate($date, 'medium', true); ?></li>
            <?php endforeach; ?>
        </ul>

    <?php endif; ?>

    <?php $pastOrders = $_subscription->getOrders(); ?>
    <?php if(count($pastOrders) > 0): ?>
        <?php echo $this->getChildHtml('pager'); ?>
        <h2 class="table-caption"><?php echo $this->__('Past Orders') ?></h2>
        <table class="data-table" id="past-orders-table">
            <col width="1" />
            <col width="1" />
            <col />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <thead>
            <tr>
                <th><span class="nobr"><?php echo $this->__('Order #') ?></span></th>
                <th><?php echo $this->__('Date') ?></th>
                <th><?php echo $this->__('Ship To') ?></th>
                <th><span class="nobr"><?php echo $this->__('Order Total') ?></span></th>
                <th><span class="nobr"><?php echo $this->__('Order Status') ?></span></th>
                <th>&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($pastOrders as $order): ?>
                <?php /** @var Mage_Sales_Model_Order $order */ ?>
                <tr>
                    <td><?php echo $order->getIncrementId(); ?></td>
                    <td><span class="nobr"><?php echo $order->getCreatedAtFormated('medium'); ?></span></td>
                    <td><?php echo $order->getShippingAddress()->getName(); ?></td>
                    <td><?php echo $order->formatPrice($order->getGrandTotal()); ?></td>
                    <td><em><?php echo $order->getStatusLabel(); ?></em></td>
                    <td class="a-center">
                        <span class="nobr">
                            <a href="<?php echo $this->getUrl('sales/order/view', array('order_id' => $order->getId())); ?>">
                                <?php echo $this->__('View Order') ?></a>
                        </span>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <script type="text/javascript">decorateTable('past-orders-table');</script>
    <?php endif; ?>
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->getBackUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Subscriptions') ?></a></p>
    </div>
</div>
