<?php
/**
 *                       ######
 *                       ######
 * ############    ####( ######  #####. ######  ############   ############
 * #############  #####( ######  #####. ######  #############  #############
 *        ######  #####( ######  #####. ######  #####  ######  #####  ######
 * ###### ######  #####( ######  #####. ######  #####  #####   #####  ######
 * ###### ######  #####( ######  #####. ######  #####          #####  ######
 * #############  #############  #############  #############  #####  ######
 *  ############   ############  #############   ############  #####  ######
 *                                      ######
 *                               #############
 *                               ############
 *
 * Adyen Subscription module (https://www.adyen.com/)
 *
 * Copyright (c) 2015 H&O E-commerce specialists B.V. (http://www.h-o.nl/)
 * See LICENSE.txt for license details.
 *
 * Author: Adyen <magento@adyen.com>, H&O E-commerce specialists B.V. <info@h-o.nl>
 */
?>
<?php /** @var Adyen_Subscription_Block_Adminhtml_Subscription_View_Tabs_Scheduled_Info $this */ ?>
<?php $_subscription = $this->getSubscription(); ?>
<?php $_quote = $this->getQuote(); ?>
<?php $_billingAgreement = $this->getBillingAgreement(); ?>

<div class="box-left">
    <!--Billing Address-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-billing-address"><?php echo Mage::helper('sales')->__('Billing Address') ?></h4>
        </div>
        <fieldset>
            <address><?php echo $_quote->getBillingAddress()->format('html'); ?></address>
        </fieldset>
    </div>
</div>
<div class="box-right">
    <!--Shipping Address-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-shipping-address"><?php echo Mage::helper('sales')->__('Shipping Address') ?></h4>
        </div>
        <fieldset>
            <address><?php echo $_quote->getShippingAddress()->format('html'); ?></address>
        </fieldset>
    </div>
</div>
<div class="clear"></div>

<div class="box-left">
    <!--Payment Info-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-billing-address"><?php echo Mage::helper('adyen_subscription')->__('Billing Agreement Information'); ?></h4>
        </div>

        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <?php if ($_billingAgreement->getId()): ?>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('adyen_subscription')->__('Reference ID'); ?></label></td>
                        <td class="value">
                            <a href="<?php echo $this->getBillingAgreementViewUrl();?>" target="_blank">
                                <strong><?php echo $_billingAgreement->getReferenceId(); ?></strong>
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('adyen_subscription')->__('Status'); ?></label></td>
                        <td class="value"><strong><?php echo $_billingAgreement->getStatusLabel(); ?></strong></td>
                    </tr>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('adyen_subscription')->__('Method'); ?></label></td>
                        <td class="value"><strong><?php echo $_billingAgreement->getPaymentMethodInstance() ? $_billingAgreement->getPaymentMethodInstance()->getTitle() : ''; ?></strong></td>
                    </tr>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('adyen_subscription')->__('Created At'); ?></label></td>
                        <td class="value"><strong><?php echo $_billingAgreement->getCreatedAt(); ?></strong></td>
                    </tr>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('adyen_subscription')->__('Label'); ?></label></td>
                        <td class="value"><strong><?php echo $_billingAgreement->getAgreementLabel(); ?></strong></td>
                    </tr>
                <?php else: ?>
                    <tr>
                        <td class="label"><em></em><?php echo Mage::helper('adyen_subscription')->__('No Billing Agreement'); ?></em></td>
                    </tr>
                <?php endif; ?>
            </table>
        </div>
    </div>
</div>
<div class="box-right">
    <!--Shipping Info-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-shipping-address"><?php echo Mage::helper('adyen_subscription')->__('Shipping &amp; Handling Information'); ?></h4>
        </div>
    </div>
    <div class="fieldset">
        <table cellspacing="0" class="form-list">
            <tr>
                <td class="label"><label><?php echo Mage::helper('adyen_subscription')->__('Shipping Method Code'); ?></label></td>
                <td class="value"><strong><?php echo $_quote->getShippingAddress()->getShippingMethod(); ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label><?php echo Mage::helper('adyen_subscription')->__('Shipping Method Title'); ?></label></td>
                <td class="value"><strong><?php echo $this->getShippingMethodTitle(); ?></strong></td>
            </tr>
        </table>
    </div>
</div>

<div class="clear"></div>
